import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
          <head>
              <meta property="og:title" content="The Desperate Trader" />
              <meta property="og:description" content="Join The Desperate Trader for real-time stock alerts, watchlists, and expert trading insights." />
              <meta property="og:image" content="https://main.d1bn172j23wjtb.amplifyapp.com/og-image.jpeg" />
              <meta property="og:url" content="https://main.d1bn172j23wjtb.amplifyapp.com/" />
              <meta property="og:type" content="website" />
          </head>
          <body>{children}</body>
      </html>
  );
}


